ministryofjustice/iis

- .snyk
- circle.yml
- package.json
- server/app.js
- server/config.js
- test/auditing.js
1. Use secure cookie when node env == prod
2. Update dependencies to address vulnerabilities reported by Snyk
3. Add snyk protect to npm scripts
4. Add Helmet for HTTP header security vulnerability protection 
5. Disable x-powered-by header
As per https://expressjs.com/en/advanced/best-practice-security.html
? Should we also be setting cookie domain in prod ?
> Secure code

- data/audit.js
- data/search.js
- data/subject.js
- data/utils.js
- log.js
- routes/disclaimer.js
- routes/index.js
- routes/search.js
- routes/subject.js
- server/app.js
- server/db.js
- test/auditing.js
- views/search/results.jade
- views/subject.jade
- views/subject/offences.jade
- views/subject/summary.jade
No idea if this works but added a rewriter using your flatten function
> Rewrite azure log message via flattening

- data/names.js
- test/form-names-validation.js
Allow name search with apostrophe, hyphen, and space
> Nhpa 86 special chars search

- assets/javascripts/search/searchValidators.js
- controllers/searchController.js
- data/identifier.js
- data/search.js
- test/client/searchValidatorsTest.js
- test/form-prison-number-validation.js
- test/search.js
- views/search/identifier.jade
Add cro and pnc inputs to identifier search form
Reject if no inputs or invlaid prison number
Allow any CRO or PNC
> Searchby cro pnc

- data/codes.js
- data/subject.js
- test/subject.js
- views/subject/hdcinfo.jade
Add extra line on HDC history entries to show HDC reason
> Display HDC reason on HDC history

- log.js
- server.js
- server/misc.js
This makes it easier to set up automated alerting on it via Azure Log Analytics
https://trello.com/c/Z67sZszC/135-application-healthchecks
> Record healthy periodic healthcheck as appinsight event

- data/search.js
- data/subject.js
- data/utils.js
- package.json
- test/search.js
- test/subject.js
- views/search/results.jade
- views/subject.jade
Switched to Case instead of change-case because it keeps punctuation
> Use a case change library that preserves punctuation

- data/codes.js
- data/codes/religionCodes.json
- data/subject.js
- test/subject.js
> Add religion to subject info

- controllers/subjectController.js
- data/content.js
- data/subject.js
- test/subject.js
- views/subject/sentences.jade
- views/subject/summary.jade
> Eff sen hist 2

- controllers/searchController.js
- controllers/subjectController.js
- data/content.js
- server/db.js
SearchController:
- add error title and desc to correct structure for page render
- lookup specific error message based on DB error code (allows for adding other more specific messages when identified)
SubjectController:
- Use general DB error message rather than misleading "incorrect identifier" message
> Handle DB errors with specific messages

- views/search/results2.jade
- views/subject2/movements.jade
Fix display of alias names in search results
Fix case of movement description
> Minor fixes

- controllers/helpers/textHelpers.js
- test/auditing.js
- views/subject2/addresses.jade
Add a few acronymns that appear in addresses
> Add acronyms that appear in addresses

- controllers/helpers/suggestionHelpers.js
- controllers/searchController.js
- data/content.js
- routes/search.js
- test/controllers/helpers/suggestionHelpersTest.js
- test/controllers/searchControllerTest.js
- views/search/results.jade
- views/search/suggestions.jade
Generate search suggestions based on query terms
Show page of suggestions
Apply selected suggestion and perform search
> Add suggestions page with suggested new search terms

- .circleci/config.yml
> HAAR-177: deploy stage should be dependent on unit tests

- .circleci/config.yml
> HAAR-177: run npm task record-build-info during deploy

- .circleci/config.yml
> HAAR-177: pull in circle ci envs so we can use them in the deploy stag

- .circleci/config.yml
> HAAR-177: tweak formatting of circle ci env names

- .circleci/config.yml
> HAAR-177: tweak formatting of circle ci env names; temporarily change branch filter so can test on this branch

- .circleci/config.yml
> HAAR-177: circle ci deploy from main

- .circleci/config.yml
- audit-ci.json
- package.json
> HAAR-177: add security pipeline

- .circleci/config.yml
> HAAR-177: update alerts-slack-channel to haar channel
